apiVersion: v1
kind: ConfigMap
metadata:
  name: my-app-config
data:
  index.html: |
    <!DOCTYPE html>
    <html>
    <head>
      <title>My Portfolio</title>
    </head>
    <body>
    <h1>Hello from Keshav's Portfolio</h1>
    <p>Deployed via Harness CI/CD on Kubernetes!</p>
    </body>
    </html>
---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-app
  template:
    metadata:
      labels:
        app: my-app
    spec:
      containers:
        - name: my-app
          image: nginx:latest
          ports:
            - containerPort: 80
          volumeMounts:
            - name: app-volume
              mountPath: /usr/share/nginx/html
      volumes:
        - name: app-volume
          configMap:
            name: my-app-config
---

apiVersion: v1
kind: Service
metadata:
  name: my-app-svc
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 80
  selector:
    app: my-app